-- AlterTable
ALTER TABLE "Ingredient" ADD COLUMN     "bagQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bagWeight" DOUBLE PRECISION NOT NULL DEFAULT 50;

-- AlterTable
ALTER TABLE "InventoryTransaction" ADD COLUMN     "bagQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bagWeight" DOUBLE PRECISION NOT NULL DEFAULT 50;
