-- AlterTable
ALTER TABLE "public"."ProductionBatch" ADD COLUMN     "breadPrice" DOUBLE PRECISION NOT NULL DEFAULT 100000,
ADD COLUMN     "totalSale" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "waterUsed" DOUBLE PRECISION NOT NULL DEFAULT 25;
